### ISSUE TITLE
useDLACore=0 error

### ISSUE THREAD

**Issue by Vulcan-YJX** [NVIDIA-ISAAC-ROS/isaac_ros_proximity_segmentation#10]
- hardware: jetson orin agx
- system: jetpack 5.1

when i use trt to cover onnx to plan with DLA. Throw an error about
` 
[optimizer.cpp::checkIfDirectIOIsPossible::4316] Error Code 4: Internal Error (BuilderFlag::kDIRECT_IO specified but no conformant implementation exists)

[builder.cpp::buildSerializedNetwork::751] Error Code 2: Internal Error (Assertion engine != nullptr failed. )
`

**Comment by jaiveersinghNV** [comment]
Could you please try again with the latest [Isaac ROS DP3 release](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_proximity_segmentation/releases/tag/v0.30.0-dp)?

Specifically, the command to convert the model from `.onnx` to `.plan` has been updated to use an additional flag for `--allowGPUFallback`:

```bash
/usr/src/tensorrt/bin/trtexec --saveEngine=/tmp/models/bi3d/bi3dnet_featnet.plan \
--onnx=/tmp/models/bi3d/featnet.onnx \
--int8 --useDLACore=0 --allowGPUFallback &&
/usr/src/tensorrt/bin/trtexec --saveEngine=/tmp/models/bi3d/bi3dnet_segnet.plan \
--onnx=/tmp/models/bi3d/segnet.onnx \
--int8 --useDLACore=0 --allowGPUFallback
```

**Comment by Vulcan-YJX** [comment]
Thanks, it works.
