### ISSUE TITLE
bi3d_output not shown

### ISSUE THREAD

**Issue by jocacace** [NVIDIA-ISAAC-ROS/isaac_ros_proximity_segmentation#4]
Hi guys,

I am successfully able to run the example using the nvidia docker. I am using the following command:

```
ros2 run isaac_ros_bi3d isaac_ros_bi3d_visualizer.py \
--rosbag_path /workspaces/isaac_ros-dev/src/isaac_ros_proximity_segmentation/resources/rosbags/bi3dnode_rosbag/ \
--max_disparity_value 50
```

However, I am able to get the image from rqt (the input image), while I am not able to get the bi3d_output. The image windows is not open and I cannot see the result of the segmentation. Do you have any hint?

Regards,

**Comment by jaiveersinghNV** [comment]
The output from the Isaac ROS Bi3D node is a ROS2 `DisparityImage`, not a regular ROS2 `Image`. As a result, this output topic cannot be visualized in tools like `rqt` or `rviz`. This is why we provide the standalone `isaac_ros_bi3d_visualizer.py` script.
