### ISSUE TITLE
quasi stereo images

### ISSUE THREAD

**Issue by benkelaci** [NVIDIA-ISAAC-ROS/isaac_ros_proximity_segmentation#7]
Hi,

Do you think it work with images those are not from a stereo camera? E.g.: 2x images that was made from 5-10 meter away (but they are pointing to the same direction)

Thank you

**Comment by gordongrigor** [comment]
Unlikely.  

Stereo perception functions require precise calibration for intrinsic and extrinsic parameters.  These perception functions rely on  [Epipolar geometry](https://en.wikipedia.org/wiki/Epipolar_geometry) with left and right camera on the same plane, within a tight mechanical tolerance so they are pointing the same direction. 

DNN's such as BI3D used in proximity segmentation can be robust to some variation, however two camera's roughly in the right position and direction would lack the calibration and mechanical tolerance for this predictive function to work.
